### ISSUE TITLE
dangeabunea / pluralsight-testcafe-weabapp: Project compile failure

### ISSUE THREAD

**Issue by odacrd** [dangeabunea/pluralsight-testcafe-weabapp#1]
Using..
Angular CLI: 10.1.6
Node: 21.1.0
OS: win32 x64

Angular: 10.1.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.6
@angular-devkit/build-angular   0.1001.6
@angular-devkit/core            10.1.6
@angular-devkit/schematics      10.1.6
@angular/cli                    10.1.6
@schematics/angular             10.1.6
@schematics/update              0.1001.6
rxjs                            6.6.3
typescript                      4.0.3

**As per course instruction, I execute as follows, but the compile fails. (Note, npm install reported 89 vulnerabilities (3 low, 30 moderate, 46 high, 10 critical)**

PS C:\PS\TestCafe\webapp> ng serve
Node.js version v21.1.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/previous-releases/.
(node:888) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
10% building 3/3 modules 0 active(node:888) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
10% building 3/4 modules 1 active ...ient\index.js?http://0.0.0.0:0/sockjs-node&sockPath=/sockjs-nodenode:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^
Error: error:308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\PS\TestCafe\webapp\node_modules\webpack\lib\util\createHash.js:135:53)      
    at NormalModule._initBuildHash (C:\PS\TestCafe\webapp\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\PS\TestCafe\webapp\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\PS\TestCafe\webapp\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\PS\TestCafe\webapp\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\PS\TestCafe\webapp\node_modules\loader-runner\lib\LoaderRunner.js:203:19
    at VirtualFileSystemDecorator.readFile (C:\PS\TestCafe\webapp\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:47:13)
    at processResource (C:\PS\TestCafe\webapp\node_modules\loader-runner\lib\LoaderRunner.js:202:11)  
    at iteratePitchingLoaders (C:\PS\TestCafe\webapp\node_modules\loader-runner\lib\LoaderRunner.js:158:10)
    at runLoaders (C:\PS\TestCafe\webapp\node_modules\loader-runner\lib\LoaderRunner.js:365:2)        
    at NormalModule.doBuild (C:\PS\TestCafe\webapp\node_modules\webpack\lib\NormalModule.js:295:3)    
    at NormalModule.build (C:\PS\TestCafe\webapp\node_modules\webpack\lib\NormalModule.js:446:15)     
    at Compilation.buildModule (C:\PS\TestCafe\webapp\node_modules\webpack\lib\Compilation.js:739:10) 
    at C:\PS\TestCafe\webapp\node_modules\webpack\lib\Compilation.js:981:14 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v21.1.0
PS C:\PS\TestCafe\webapp>

**Comment by dangeabunea** [comment]
Hello! There appeared to be some pretty old dependencies that no longer work in up-to-date environments. I updated the project to use Angular 17 and tested it on two machines. Everything should now be ok.

**Comment by odacrd** [comment]
Thank you , Dan.Sent from my iPhoneOn Mar 20, 2024, at 5:34 AM, Dan Geabunea ***@***.***> wrote:﻿
Hello! There appeared to be some pretty old dependencies that no longer work in up-to-date environments. I updated the project to use Angular 17 and tested it on two machines. Everything should now be ok.

**Comment by odacrd** [comment]
Thank you!
